
(defun sweyla732203 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/732203/"
  (interactive)
  (color-theme-install
   '(sweyla732203
     ((background-color . "#030306")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#4E97FA" :italic "true"))))
     (font-lock-py-decorators-face ((t (:foreground "#4E97FA"))))
     (font-lock-constant-face ((t (:foreground "#6EFFDB"))))
     (font-lock-builtin-face ((t (:foreground "#7A8879"))))
     (font-lock-function-name-face ((t (:foreground "#FFFF90"))))
     (font-lock-variable-name-face ((t (:foreground "#7F9884"))))
     (font-lock-keyword-face ((t (:foreground "#FFDD69"))))
     (font-lock-string-face ((t (:foreground "#ABFF46"))))
     (font-lock-doc-string-face ((t (:foreground "#ABFF46"))))
     (font-lock-type-face ((t (:foreground "#B8EFDA"))))
     )))

(provide 'sweyla732203)
